title:            "Sinemap"
tagline:          "Sinema yazıları"
description:      "Sinema ve TV üzerine yazılar ve film eleştirileri."
canonical:        "https://sinemap.netlify.app"
url: "https://sinemap.netlify.app" 
logo: "/icons/avatar.png"
locale: "tr_TR"
twitter: "https://twitter.com/Sinemap4"

# Owner/author information
author:
  name:           "Ufuk Kızılgedik"
  bio:            "Sinemap Editörü"
  email:          "sinemapmail@gmail.com"
  twitter:        "https://twitter.com/Ufuk_Kizilgedik"

tools:
  standards:      "HTML, SCSS, Jekyll"
  software:       "git"

# Open Graph customization
opengraph:
  locale:  "tr_TR"
  
  # Site settings
lang: tr

# Links to include in top navigation
# For external links add external: true
links:
  - title: YAZILAR
    url: /
  - title: BLOG
    url: /blog
  - title: ARA
    url: /ara

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Turkey
future:      true
highlighter: rouge

# Jekyll configuration
permalink: /filmler/:title/

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

include: [".htaccess", "_pages"]

exclude: ["vendor",
          "_assets",
          "Gemfile",
          "Gemfile.lock",
          "gulpfile.js",
          "node_modules",
          "package.json"]

# My additions  
  
plugins:
  - jekyll-paginate-v2
  - jekyll-figure
  - jekyll-sitemap
    
collections:
  blog:
    output: true
    permalink: /:collection/:title/

defaults: 
  - 
    scope: 
        path: ""
        type: "posts"
    values: 
        layout: "post"
        master: "true" #this is for looping through all documents in feed.xml
        image: /assets/img/featured/placeholder-960.jpg
  -
    scope:
      path: _pages
      type: "pages"
    values:
      layout: "page"
      image: /assets/img/featured/placeholder-960.jpg
  -
    scope:
      path: _blog
      type: "blog"
    values:
      layout: "post"
      master: "true"

pagination:
  enabled: true
  debug: false
  per_page: 11
  permalink: '/sayfa/:num/'
  title: ':title - Sayfa :num'
  sort_reverse: true
    
autopages:
  enabled: true
  categories:
    enabled: false
  collections:
    enabled: false
  tags:
    enabled: true
    layouts:
      - "tags.html"
    title: ":tag filmleri" # :tag is replaced by the tag name
    slugify:
      mode: 'latin'
      cased: true
    permalink: "/etiket/:tag"

jekyll-figure:
  paragraphs: false