title:            "Karateke"
tagline:          "Toplum, insan, kitap ve sinema üzerine yazılar"
description:      "Toplum, insan, kitap ve sinema üzerine yazılar. Eleştirel düşüncenin adresi."
canonical:        "https://karateke.github.io"
url: "https://karateke.github.io" 
logo: "/icons/avatar.png"
locale: "tr_TR"
twitter: "https://twitter.com/Karateke19"

# Owner/author information
author:
  name:           "Ufuk Kizilgedik"
  bio:            "A sweet boi named Karateke"
  email:          "karateke.github@gmail.com"
  twitter:        "https://twitter.com/Ufuk_Kizilgedik"
  
social: 
    name: "Karateke"
    links: 
        - "https://twitter.com/Ufuk_Kizilgedik"
        - "https://www.facebook.com/mormamut"
        - "https://www.instagram.com/klapsimo/"
  
google_analytics: "UA-128618889-1"

tools:
  standards:      "HTML, SCSS, Jekyll"
  software:       "git"

# Open Graph customization
opengraph:
  locale:  "tr_TR"
  
  # Site settings
lang: tr

# Links to include in top navigation
# For external links add external: true
links:
  - title: YAZILAR
    url: /
  - title: NOTLAR
    url: /notlar
  - title: KİTAP
    url: /kitap
  - title: FİLM
    url: /film
  - title: ARA
    url: /ara

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Turkey
future:      true
highlighter: rouge

# Jekyll configuration
permalink: /:categories/:title/

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

include: [".htaccess", "_pages"]

exclude: ["vendor",
          "_assets",
          "Gemfile",
          "Gemfile.lock",
          "gulpfile.js",
          "node_modules",
          "package.json"]

# My additions  
  
plugins:
  - jekyll-paginate-v2
  - jekyll-figure
  - jekyll-sitemap
    
collections:
  notlar:
    output: true
    permalink: /:collection/:title/
  kitaplar:
    output: true
    permalink: /:collection/:title/
  filmler:
    output: true
    permalink: /:collection/:title/
  cizimler:
    output: false
    permalink: /cizimler/

defaults: 
  - 
    scope: 
        path: ""
        type: "posts"
    values: 
        layout: "post"
        master: "true" #this is for looping through all documents in feed.xml 
        image: /assets/img/featured/placeholder-960.jpeg
  -
    scope:
      path: _pages
      type: "pages"
    values:
      layout: "page"
      image: /assets/img/featured/placeholder-960.jpeg
  -
    scope:
      path: _notlar
      type: "notlar"
    values:
      layout: "note"
      master: "true"
  -
    scope:
      path: _kitaplar
      type: "kitaplar"
    values:
      layout: "note"
      master: "true"
  -
    scope:
      path: _filmler
      type: "filmler"
    values:
      layout: "note"
      master: "true"

pagination:
  enabled: true
  debug: false
  per_page: 11
  permalink: '/sayfa/:num/'
  title: ':title - Sayfa :num'
  sort_reverse: true
    
autopages:
  enabled: true
  categories:
    enabled: true
    layouts:
      - "kategori.html"
    title: ":cat kategorisindeki tüm yazılar" # :cat is replaced by the cat name
    slugify:
      mode: 'latin'
      cased: true
    permalink: "/:cat"
  collections:
    enabled: false
  tags:
    enabled: true
    layouts:
      - "tags.html"
    title: ":tag etiketine sahip tüm yazılar" # :tag is replaced by the tag name
    slugify:
      mode: 'latin'
      cased: true
    permalink: "/etiket/:tag"

jekyll-figure:
  paragraphs: false